let constants = {};

constants.DISPLAY_VISUAL = 'DISPLAY_VISUAL';
constants.DISPLAY_AUDITIVE = 'DISPLAY_AUDITIVE';
constants.DISPLAY_HAPTIC = 'DISPLAY_AUDITIVE';
constants.USAGE_HAPTIC = 'USAGE_HAPTIC';
constants.USAGE_SPEECH = 'USAGE_SPEECH';
constants.USAGE_TOUCH = 'USAGE_TOUCH';
constants.USAGE_GENERAL = 'USAGE_GENERAL';


constants.EVENT_DB_CONNECTION_LOST = 'EVENT_DB_CONNECTION_LOST';
constants.EVENT_DB_PULL_UPDATED = 'EVENT_DB_PULL_UPDATED';
constants.EVENT_DB_UNAUTHORIZED = 'EVENT_DB_UNAUTHORIZED';
constants.EVENT_DB_SYNC_STATE_CHANGE = 'EVENT_DB_SYNC_STATE_CHANGE';
constants.EVENT_DB_INITIALIZED = 'EVENT_DB_INITIALIZED';
constants.EVENT_DB_CLOSED = 'EVENT_DB_CLOSED';
constants.EVENT_DB_DATAMODEL_UPDATE = 'EVENT_DB_DATAMODEL_UPDATE';

export {constants};